### ISSUE TITLE
1.0.0 Issue

### ISSUE THREAD

**Issue by denizcdursun** [jvines/astroARIADNE#44]
Hello @jvines,

The new version is great, my old problems are solved. But now I can't do "f.prior_setup", which I used to be able to do easily. The error I get is as follows;

` f.prior_setup = {
        'teff': ('normal', 6050, 50),
        'logg': ('default'), #('normal', 4.21, 0.05),
        'z':  ('default'),
        'dist': ('default'),
        'rad': ('default'),
        'Av': ('default')
    }`

`Traceback (most recent call last):
  File "HD_182758.py", line 56, in <module>
    f = Fitter()
  File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/fitter.py", line 105, in __init__
    self.grid = 'phoenix'
  File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/fitter.py", line 189, in grid
    self._interpolator = DFInterpolator(pd.read_pickle(intp))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/pickle.py", line 217, in read_pickle
    return pickle.load(handles.handle)  # type: ignore[arg-type]
OSError: [Errno 5] Input/output error`

**Comment by denizcdursun** [comment]
Thank you for answer @jvines ,

It comes up when I make a change to f.prior_setup. It doesn't matter which star it is. All my models are complete. It works without error when f.prior_setup is default. 

In the previous version, I I used to change easily Teff or z as I wanted. That's why I opened the topic like this.

**Comment by denizcdursun** [comment]
`Initializing plotter.

Created the directory /Volumes/Astro-Deniz/astroARIADNE-master-3/Outputs/plots
Created the directory /Volumes/Astro-Deniz/astroARIADNE-master-3/Outputs/plots/histograms
Grid btsettl loaded.

Plotter initialized.

Plotting SED
Traceback (most recent call last):
  File "HD_182758.py", line 84, in <module>
    artist.plot_SED()  # Plots stellar SED with model included
  File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 412, in plot_SED
    self.SED(ax)
  File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 593, in SED
    wave, flux = self.fetch_btsettl()
  File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 1293, in fetch_btsettl
    selected_SED = gl[0]
IndexError: list index out of range`

**Comment by jvines** [comment]
This other error is unrelated to the first one.

Can you provide a reproducible example for the first issue?

For the second one I would also need a reproducible example.

**Comment by denizcdursun** [comment]
Hello again @jvines, sorry for the late reply.
I'm using your code for 100 different metal-poor stars. I have now completed my 50 stars. I list the problems I encountered:

1 - I always got an error when the model "btsettl" was selected as the most compatible model for my star.

> Grid btsettl loaded.
> Plotter initialized.
> 
> Plotting SED
> Traceback (most recent call last):
>   File "test_bma.py", line 87, in <module>
>     artist.plot_SED()  # Plots stellar SED with model included
>   File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 412, in plot_SED
>     self.SED(ax)
>   File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 604, in SED
>     new_w = np.linspace(wave[0], wave[-1], len(wave))
> IndexError: index 0 is out of bounds for axis 0 with size 0


2 - I got multiple "pandas/pickle.py in read_pickle" errors when phoenix model was selected as the most compatible model for my star.

> Traceback (most recent call last):
>   File "test_bma.py", line 60, in <module>
>     f = Fitter()
>   File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/fitter.py", line 105, in __init__
>     self.grid = 'phoenix'
>   File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/fitter.py", line 189, in grid
>     self._interpolator = DFInterpolator(pd.read_pickle(intp))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/io/pickle.py", line 217, in read_pickle
>     return pickle.load(handles.handle)  # type: ignore[arg-type]
> OSError: [Errno 5] Input/output error

3 - "STROMGREN_u" and "GALEX_(fuv or nuv)" were incompatible in the SED profiles for all my stars.

PS: I am using your code in our paper (which we are currently working on) and in my thesis. My conference paper has been accepted for publication. You will see it when it is published.

**Comment by jvines** [comment]
Dear @denizcdursun ,

Please provide reproducible examples for your errors.

As for number 3, what I can assume is there is a mismatch in the crossmatch for your stars. I've had that issue *some* times, though not all of them. If you happen to have magnitudes which you know are correct, you can add them manually with the `add_mag` method from the `Star` class.

Cheers.

**Comment by denizcdursun** [comment]
> Dear @denizcdursun ,
> 
> Please provide reproducible examples for your errors.
> 
> As for number 3, what I can assume is there is a mismatch in the crossmatch for your stars. I've had that issue _some_ times, though not all of them. If you happen to have magnitudes which you know are correct, you can add them manually with the `add_mag` method from the `Star` class.
> 
> Cheers.

I don't understand what you mean by reproducible example. For example; 

```
    ra = 308.215
    dec = 41.898
    starname = 'HD 195987'
    gaia_id = 2067948245320365184
```
for this star i get the 1st error. All files are ok but when plotting the SED it gives this error. I guess it can't find self.SED(ax)

Here is the star example for the my second problem. The read_pickle command is giving errors in the new version of the pandas library. I think this might be the reason.

```
    ra = 295.440
    dec = 43.747
    starname = 'HD 186306'
    gaia_id = 2078105327586616704

```

I've updated all my model files and nothing is missing.

**Comment by denizcdursun** [comment]
Hello @jvines,

My previous problems still persist (there is a general problem about BT-Settl). 

Also, stars that are determined to be metal-poor in the literature,  more metal-rich in the Ariadne values.. What is the main reason for this? (We consider your limitations about the models in your article.)

Ex: BD+592407 
Literature [Fe_H] = -1,65 
Ariadne: [Fe_H] = -0,30

**Comment by denizcdursun** [comment]
I understand you very well because I am writing a my thesis. I look forward to hearing from you when you are available for the others. I have to fix these problems for our article..

**Comment by jvines** [comment]
@denizcdursun hi, about your first error:

>1 - I always got an error 
>
> when the model "btsettl" was selected as the most compatible model for my star.
> 
>> Grid btsettl loaded.
> Plotter initialized.
>>
>> Plotting SED
> Traceback (most recent call last):
> File "test_bma.py", line 87, in
> artist.plot_SED() # Plots stellar SED with model included
> File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 412, in plot_SED
> self.SED(ax)
> File "/Volumes/Astro-Deniz/astroARIADNE-master-3/astroARIADNE/plotter.py", line 604, in SED
> new_w = np.linspace(wave[0], wave[-1], len(wave))
> IndexError: index 0 is out of bounds for axis 0 with size 0

Can you verify your BT-Settl models (used for plotting) are correct and not empty?

**Comment by denizcdursun** [comment]
> Can you verify your BT-Settl models (used for plotting) are correct and not empty?

<img width="984" alt="Ekran Resmi 2023-02-16 11 36 46" src="https://user-images.githubusercontent.com/79997767/219312051-ca2c42f4-d5a5-4f6c-92eb-d6eda107edd6.png">

All my models are complete..

**Comment by jvines** [comment]
Sorry, I should've been more precise. Have you verified those files have data in them? Last time I checked the BT-Models hosted on the phoenix website didn't have any data on them anymore and the fits files were all empty

**Comment by denizcdursun** [comment]
> Sorry, I should've been more precise. Have you verified those files have data in them? Last time I checked the BT-Models hosted on the phoenix website didn't have any data on them anymore and the fits files were all empty

<img width="707" alt="Ekran Resmi 2023-02-17 14 41 55" src="https://user-images.githubusercontent.com/79997767/219644890-d1c63cb3-337a-44ea-8f2d-084cad24c20d.png">

I randomly checked inside the BT-Settl files and they are not empty.  I don't get any errors on other models. I don't know why, when BT-Settl model is selected as compatible, the program gives the error I mentioned.

**Comment by jvines** [comment]
Hi @denizcdursun , I'm sorry, I think those fits files are empty, see NAXIS = 0? Could you try actually plotting the data inside them?

**Comment by denizcdursun** [comment]
Where can I find non-empty fit files? It took me a long time to download these files..

**Comment by jvines** [comment]
You might find luck here: [https://phoenix.ens-lyon.fr/Grids/](https://phoenix.ens-lyon.fr/Grids/)

**Comment by denizcdursun** [comment]
Thank you very much!
I want to get confirmation so that there is no error. Which folder here works for us?

<img width="542" alt="Ekran Resmi 2023-02-23 19 36 40" src="https://user-images.githubusercontent.com/79997767/220971352-ba132806-0ea9-468c-8c49-12ddcb0d55aa.png">

**Comment by jvines** [comment]
I'm not sure, as I downloaded the models from the phoenix site before they were nuked. My educated guess is the Spectra folder, but you'll have to find out yourself.

The other solution would be forcing ARIADNE to use some other model for plotting

**Comment by denizcdursun** [comment]
> I'm not sure, as I downloaded the models from the phoenix site before they were nuked. My educated guess is the Spectra folder, but you'll have to find out yourself.
> 
> The other solution would be forcing ARIADNE to use some other model for plotting

Thank you very much again for your help.
