### ISSUE TITLE
'SFD': SFDQuery, NameError: name 'SFDQuery' is not defined

### ISSUE THREAD

**Issue by mdredyanahmed** [jvines/astroARIADNE#59]
Though SFDquery is defined in star.py, I am having following error:
Holoviews not imported. Some visualizations will not be available.
/Users/mdredyanahmed/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
PyMultiNest not imported.  MultiNest fits will not work.
/Users/mdredyanahmed/astroARIADNE/astroARIADNE/fitter.py:43: UserWarning: (py)MultiNest installation (or libmultinest.dylib) not detected.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/mdredyanahmed/astroARIADNE/run.py", line 3, in <module>
    from astroARIADNE.star import Star
  File "/Users/mdredyanahmed/astroARIADNE/astroARIADNE/__init__.py", line 14, in <module>
    from .star import Star
  File "/Users/mdredyanahmed/astroARIADNE/astroARIADNE/star.py", line 46, in <module>
    class Star:
  File "/Users/mdredyanahmed/astroARIADNE/astroARIADNE/star.py", line 126, in Star
    'SFD': SFDQuery,
NameError: name 'SFDQuery' is not defined

can anyone help me to resolve it?
can anyone say me how can I install Holoviews ?
It maybe mentioned here my machine is macbook pro m1.

I also tried to download Phoenix v2 model, Phoenix v2 wavelength file and BT-Models but it is not working. Can anyone say me how to download it? Directly, it is not downloading.

**Comment by jvines** [comment]
Your installation of dustmaps is missing the actual dustmaps... Refer to their documentation for full instructions on how to obtain the dustmaps.
